app/models/__init__.py
from flask import Blueprint

bp = Blueprint('models', __name__)

from app.models.teams import Team
from app.models.fixtures import Fixture
from app.models.gameweeks import Gameweek
from app.models.results import Result
from app.models.current_gameweek import CurrentGameweek

app/models/current_gameweek.py
from app.extensions import db


class CurrentGameweek(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    gameweek_number = db.Column(db.Integer, nullable=False)

    def __init__(self, gameweek_number):
        self.gameweek_number = gameweek_number

app/models/fixtures.py
from app.extensions import db


class Fixture(db.Model):
    fixture_id = db.Column(db.Integer, primary_key=True)
    gameweek_id = db.Column(db.Integer, db.ForeignKey('gameweek.gameweek_id'),
                            nullable=False)
    home_team_id = db.Column(db.Integer, db.ForeignKey('team.team_id'),
                             nullable=False)
    away_team_id = db.Column(db.Integer, db.ForeignKey('team.team_id'),
                             nullable=False)

    # Define relationships with the Team and Gameweek tables
    home_team = db.relationship('Team', foreign_keys=[home_team_id])
    away_team = db.relationship('Team', foreign_keys=[away_team_id])
    gameweek = db.relationship('Gameweek')

app/models/gameweeks.py
from app.extensions import db


class Gameweek(db.Model):
    gameweek_id = db.Column(db.Integer, primary_key=True)
    gameweek_number = db.Column(db.Integer, nullable=False)

app/models/results.py
from app.extensions import db


class Result(db.Model):
    result_id = db.Column(db.Integer, primary_key=True)
    fixture_id = db.Column(db.Integer, db.ForeignKey('fixture.fixture_id'),
                           nullable=False)
    home_team_score = db.Column(db.Integer, nullable=False)
    away_team_score = db.Column(db.Integer, nullable=False)

    # Define a relationship with the Fixture table
    fixture = db.relationship('Fixture')

app/models/teams.py
from app.extensions import db


class Team(db.Model):
    team_id = db.Column(db.Integer, primary_key=True)
    team_name = db.Column(db.String(100), nullable=False)
    team_image = db.Column(db.String(100))
    home_difficulty = db.Column(db.Integer)
    away_difficulty = db.Column(db.Integer)
    abbreviation = db.Column(db.String(10), nullable=True)

app/__init__.py
from flask import Flask

from app.extensions import db, migrate
from config import db_uri


def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = db_uri

    db.init_app(app)
    migrate.init_app(app, db)

    from app.models import bp as models_bp
    app.register_blueprint(models_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, request
from app.main import bp
from app.utilities.fixture_utilities import (calculate_team_fixture_difficulty,
                                             get_fixture)
from app.models import CurrentGameweek


@bp.route('/', methods=['GET'])
def fixtures():
    current_gameweek = CurrentGameweek.query.first()
    current_gameweek = current_gameweek.gameweek_number

    min_gameweek = int(request.args.get('min_gameweek', current_gameweek))
    max_gameweek = int(request.args.get('max_gameweek', min_gameweek + 5))

    sorted_teams, team_fixture_difficulties = calculate_team_fixture_difficulty(min_gameweek, max_gameweek)

    return render_template('index.html', teams=sorted_teams, fixtures=fixtures,
                           team_difficulties=team_fixture_difficulties,
                           min_gameweek=min_gameweek,
                           max_gameweek=max_gameweek, get_fixture=get_fixture)

app/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>FDR Tool</title>
    <link
      href="{{ url_for('static', filename='img/favicons/favicon-32x32.png')}}"
      rel="icon"
      sizes="32x32"
      type="image/png"
    />
    <link
      href="{{ url_for('static', filename='img/favicons/favicon-16x16.png')}}"
      rel="icon"
      sizes="16x16"
      type="image/png"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css')}}"
    />
  </head>
  <body>
    <div class="container">
      <div class="title">
        <h3>Fixture Difficulty Rating (FDR)</h3>
      </div>

      <div class="bmc">
        <script
          type="text/javascript"
          src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js"
          data-name="bmc-button"
          data-slug="marlonoloo"
          data-color="#00ff87"
          data-emoji=""
          data-font="Cookie"
          data-text="Buy me a coffee"
          data-outline-color="#000000"
          data-font-color="#000000"
          data-coffee-color="#FFDD00"
        ></script>
      </div>

      <form
        method="get"
        action="{{ url_for('main.fixtures') }}"
        class="range-form"
      >
        <div class="range-input">
          <label for="min_gameweek">Min Gameweek</label>
          <input
            type="number"
            name="min_gameweek"
            id="min_gameweek"
            value="{{ min_gameweek }}"
          />
        </div>

        <div class="range-input">
          <label for="max_gameweek">Max Gameweek</label>
          <input
            type="number"
            name="max_gameweek"
            id="max_gameweek"
            value="{{ max_gameweek }}"
          />
        </div>

        <div class="range-button">
          <input type="submit" value="Update Range" />
        </div>
      </form>

      <table class="fdr-table">
        <thead>
          <tr>
            <th class="team">Team</th>
            {% for gameweek in range(min_gameweek, max_gameweek + 1) %}
            <th class="opponent">{{ 'GW' ~ gameweek }}</th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {% for team in teams %}
          <tr>
            <td class="team team-body-name">
              <img
                class="team-logo"
                src="{{ team.team_image }}"
                alt="{{ team.team_name }} Logo"
              />
              <span class="team-name"
                >{{ team.team_name }} ({{ team_difficulties[team.team_name]
                }})</span
              >
            </td>

            {% for gameweek in range(min_gameweek, max_gameweek + 1) %}
            <td
              class="opponent opponent-abbrv"
              data-fixture-difficulty="{% set fixture = get_fixture(team.team_id, gameweek) %}
  {% if fixture %}
      {% set is_home_team = (team.team_id == fixture.home_team_id) %}
      {% set opponent_team_id = fixture.away_team_id if is_home_team else fixture.home_team_id %}
      {% set opponent_team = teams | selectattr('team_id', 'equalto', opponent_team_id) | first %}
      {% set difficulty = opponent_team.away_difficulty if is_home_team else opponent_team.home_difficulty %}
      {{ difficulty }}
  {% else %}
      0
  {% endif %}"
              style="background-color: 
    {% if difficulty == 2 %}
      rgb(1, 252, 122)
    {% elif difficulty == 3 %}
      rgb(231, 231, 231)
    {% elif difficulty == 4 %}
      rgb(255, 23, 81)
    {% elif difficulty == 5 %}
      rgb(128, 7, 45)
    {% else %}
      transparent
    {% endif %};
    color: {% if difficulty == 4 or difficulty == 5 %} white; {% else %} black; {% endif %};"
            >
              {% set fixture = get_fixture(team.team_id, gameweek) %} {% if
              fixture %} {% set opponent = fixture.home_team if
              fixture.away_team.team_id == team.team_id else fixture.away_team
              %} {{ opponent.abbreviation }} {% if fixture.home_team_id ==
              team.team_id %}(H){% else %}(A){% endif %} {% else %} No fixture
              {% endif %}
            </td>

            {% endfor %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </body>
</html>